#logging.level:
#  root: TRACE
#  org:
#    hibernate:
#      engine:
#        transaction:
#          internal: TRACE
#  org.springframework.orm: TRACE
#  org.springframework.transaction: TRACE
#  org.hibernate.hql.internal.ast: INFO

spring:
  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
    show_sql: true