spring:
  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
    show_sql: true
logging.level:
  kangwoojin.github.io: TRACE
