feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
  okhttp:
    enabled: true
  example-api:
    url: "http://localhost:8080"

logging:
  level:
    root: debug
    sun:
      rmi: info
    javax:
      management: info
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info

