feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
  okhttp:
    enabled: true

#logging.level.kangwooijn.github.io.openfeign.feign.ExampleClient: DEBUG
logging:
  level:
    root: debug
    sun:
      rmi: info
    javax:
      management: info
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info
